spring:
  application:
    name: admin-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/admindb
      auto-index-creation: true

  # ActiveMQ Artemis Configuration
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8082

jwt:
  secret: am9pbmdpcmxhbmltYWxzaG9lYmxpbmRwbGFudGJlbGxjdXJyZW50YWRkaXRpb253YW4=