spring:
  application:
    name: admin-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/admindb

server:
  port: 8082

jwt:
  secret: am9pbmdpcmxhbmltYWxzaG9lYmxpbmRwbGFudGJlbGxjdXJyZW50YWRkaXRpb253YW4=